### ISSUE TITLE
How to push to Google Internal Track

### ISSUE THREAD

**Issue by mist3rj** [MicrosoftDocs/appcenter-docs#725]
Hi, I want to push a release from Appcenter to the Google Internal Test Track. Appcenter supports the iOS equivalent (App Store Connected Users track).

How can I do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868e3edf-f3af-950e-4f8a-ea30c392e883
* Version Independent ID: a725a1f2-fe7b-b7be-8e5e-6db22c2a756d
* Content: [Publish to Google Play Store - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay#feedback)
* Content Source: [docs/distribution/stores/googleplay.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/googleplay.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by ghost** [comment]
I would like to know if this is possible too.

**Comment by FlorisDevreese** [comment]
I would love to know that too

Also when I create a new track in Google Play Console (e.g. a second Alpha track), this new track doens't appear in the App Center

**Comment by FlorisDevreese** [comment]
Found the issue:
Google play has no API available to access the internal/custom tracks. This is why the App Center doens't show them.

source: https://stackoverflow.com/a/55573415/3506115

**Comment by Oddj0b** [comment]
Thanks for reporting it. If you like support for the Test track give a :+1: here microsoft/appcenter/issues/125

**Comment by Oddj0b** [comment]
The text have been removed.

**Comment by vincentcastagna** [comment]
Hello,

There is an AzureTask that allows to specify the Track we want to push it to ... So I guess it should be doable through appcenter now. 

``` 
 - task: GooglePlayRelease@4
          displayName: 'Publish to google play'
          inputs:
            serviceConnection: $(GooglePlayServiceConnection)
            applicationId: '$(ApplicationIdentifier)'
            action: 'SingleBundle'
            languageCode: 'en-CA'
            bundleFile: '$(Pipeline.Workspace)/$(artifactName)/*-Signed.aab'
            track: '$(PlayConsolePublishTrack)'
 ```
